<?php

namespace Database\Seeders;

use App\Models\PurchaseRequest;
use App\Models\User;
use Illuminate\Database\Seeder;

class PurchaseRequestsSeeder extends Seeder
{
    public function run(): void
    {
        // Use existing users if present; otherwise create a few
        $users = User::query()->exists() ? User::all() : User::factory(5)->create();

        // Seed a batch of purchase requests; purchase_ref_no will be auto-generated by the model
        PurchaseRequest::factory(200)
            ->recycle($users)
            ->create();
    }
}
