<?php

namespace Database\Factories;

use App\Models\PurchaseRequest;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<\App\Models\PurchaseRequest>
 */
class PurchaseRequestFactory extends Factory
{
    protected $model = PurchaseRequest::class;

    public function definition(): array
    {
        // Randomize status; adjust submitted_at accordingly
        $status = $this->faker->randomElement(['Pending', 'Approved', 'Rejected']);

        // If submitted, pick a recent timestamp; for pending, sometimes null
        $submittedAt = $status === 'Pending'
            ? $this->faker->optional(0.6)->dateTimeBetween('-10 days', 'now')
            : $this->faker->dateTimeBetween('-30 days', 'now');

        return [
            'user_id' => User::factory(),
            // Header fields (new schema)
            'title' => $this->faker->sentence(3),
            'type_procurement_id' => 1,
            'file_reference_id' => 1,
            'vot_id' => 1,
            'location_iso_code' => $this->faker->countryCode(),
            'budget' => $this->faker->randomFloat(2, 100, 10000),
            // Use canonical `notes`; model still accepts legacy `purpose` for BC
            'notes' => $this->faker->optional()->sentence(12),
            // Items JSON payload
            'items' => [
                [
                    'item_no' => 1,
                    'details' => $this->faker->words(4, true),
                    'purpose' => $this->faker->optional()->sentence(6),
                    'quantity' => $this->faker->numberBetween(1, 10),
                    'price' => $this->faker->randomFloat(2, 10, 500),
                ],
            ],
            'status' => $status,
            'submitted_at' => $submittedAt,
            'attachment_path' => $this->faker->optional(0.3)->filePath(),
            // purchase reference no will be auto-generated by the model
            'purchase_ref_no' => null,
            // soft deletes handled by model/migration defaults
        ];
    }
}
