<?php

namespace Database\Factories;

use App\Models\PurchaseRequest;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Facades\DB;

/**
 * @extends Factory<\App\Models\PurchaseRequest>
 */
class PurchaseRequestFactory extends Factory
{
    protected $model = PurchaseRequest::class;

    public function definition(): array
    {
        // Randomize status; adjust submitted_at accordingly
        $status = $this->faker->randomElement(['Pending', 'Approved', 'Rejected']);

        // If submitted, pick a recent timestamp; for pending, sometimes null
        $submittedAt = $status === 'Pending'
            ? $this->faker->optional(0.6)->dateTimeBetween('-10 days', 'now')
            : $this->faker->dateTimeBetween('-30 days', 'now');

        return [
            'user_id' => User::factory(),
            // applicant_id now stores staff_id (string) — align with the same user when possible
            'applicant_id' => function (array $attributes) {
                try {
                    $userId = $attributes['user_id'] ?? null;
                    // When using factories, user_id should already be resolved to an integer here
                    if (is_int($userId) && $userId > 0) {
                        $staff = User::query()->where('id', $userId)->value('staff_id');
                        if ($staff) {
                            return $staff;
                        }
                    }
                } catch (\Throwable $e) {
                    // fall back to generating a user below
                }
                // Fallback: create a user to derive a valid staff_id
                return User::factory()->create()->staff_id;
            },
            // Header fields (new schema)
            'title' => $this->faker->sentence(3),
            'type_procurement_id' => 1,
            'file_reference_id' => 1,
            'vot_id' => 1,
            // Prefer an existing location ISO from the DB, otherwise a sensible default
            'location_iso_code' => (function () {
                try {
                    if (DB::getSchemaBuilder()->hasTable('locations')) {
                        $iso = DB::table('locations')->inRandomOrder()->value('location_iso_code');
                        if ($iso) {
                            return $iso;
                        }
                    }
                } catch (\Throwable $e) {
                    // ignore and use fallback below
                }
                return 'MY-01';
            })(),
            'budget' => $this->faker->randomFloat(2, 100, 10000),
            // Canonical column is `note` (singular)
            'note' => $this->faker->optional()->sentence(12),
            'status' => $status,
            'submitted_at' => $submittedAt,
            'attachment_path' => $this->faker->optional(0.3)->filePath(),
            // purchase reference no will be auto-generated by the model
            'purchase_ref_no' => null,
            // soft deletes handled by model/migration defaults
        ];
    }
}
